# The onramp and offramp sections of configuration specify external sources and sinks
# to an instance of tremor-server.
#
onramp:
  - id: tcp-input         # A unique id for binding/mapping
    type: tcp             # The unique type descriptor for the onramp (tcp server)
    codec: string         # The underlying data format expected for application payload data
    preprocessors:
      - lines
    config:
      port: 5000          # The TCP port to listen on
      host: '0.0.0.0'     # The IP address to bind on ( all interfaces in this case )
      
offramp:
  - id: es-output
    type: elastic         # an elastic search offramp
    config:
      endpoints:          # this is the eleastic search host started by docker compose
        - http://elastic:9200