name: Publish

on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install tremor lexer
      run: ./.github/scripts/install-lexer.sh
    - name: Install theme
      run: ./.github/scripts/install-theme.sh
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
